export const TILE_SIZE = 32
export const SCALE = 2
export const TILE_SIZE_SCALED = TILE_SIZE * SCALE

export const DEPTHS = {
  FLOOR: 0,
  ITEMS: 10,
  ENEMIES: 20,
  PLAYER: 30,
  COMPANION: 25,
  PROJECTILES: 35,
  HUD: 100,
  DEBUG: 200,
}

export const PLAYER = {
  SPEED: 160,
  HP_MAX: 6,
  MANA_MAX: 5,
  MANA_REGEN_RATE: 1500,
  ATTACK_DAMAGE: 2,
  IFRAME_DURATION: 1500,
}

export const DEW = {
  SPEED: 170,
  FOLLOW_DISTANCE: 70,
  ATTACK_RANGE: 60,
  ATTACK_DAMAGE: 2,
  ATTACK_COOLDOWN: 1200,
  DETECT_RANGE: 220,
}

export const ENEMY = {
  MOSSLING_HP: 3,
  MOSSLING_SPEED: 70,
  MOSSLING_DAMAGE: 1,
  MOSSLING_DETECT_RANGE: 150,
  MOSSLING_PATROL_SPEED: 40,
}
